### ISSUE TITLE
Publish ScalaFX Scaladoc in SBT builld

### ISSUE THREAD

**Issue by Facsimiler** [scalafx/scalafx#138]
Add appropriate plugins to the _SBT_ build to publish _Scaladoc API_ documentation to the _ScalaFX_ web-site on _GitHub_ automatically.

**Comment by jpsacha** [comment]
ScalaFX Scaladocs are being published on Sonatype as part of the release process. The latest versions can be accessed using the badge:
![image](https://user-images.githubusercontent.com/1205408/82733287-d1854180-9ce0-11ea-915a-57bbd519dfef.png)
