### ISSUE TITLE
There is no implementation of SeparatorMenuItem

### ISSUE THREAD

**Issue by RomanHargrave** [scalafx/scalafx#173]
I am using `*_2.11 ` version `2.2.67-R10`. After noticing that there was no separator implementation that was usable when building a menu, I did a brief search of the repository and found that there is no implementation present in the project source.

If I have time to, I will look in to an addition and take out a pull request.

**Comment by jpsacha** [comment]
Thanks for pointing this out. Please implement and provide pull request. This will also require implementation of `CustomMenuItem` and related tests. 
I am planing a release within next coupe of days (this weekend). Let me know if you want to make it into this release. I can delay it for a couple of days, say till next Wednesday (Jan 21).

**Comment by RomanHargrave** [comment]
I can see about it. I am currently on vacation.

**Comment by RomanHargrave** [comment]
Pull request opened.

**Comment by RomanHargrave** [comment]
Merge of PR #177 fixes this issue.
