### ISSUE TITLE
FileChooser does not handle a the value returned when the user cancels file selection

### ISSUE THREAD

**Issue by RomanHargrave** [scalafx/scalafx#178]
`FileChooser.showOpenMultipleDialog` is a bridge method of return type `Seq[File]` that calls `javafx.stage.FileChooser`, which has a return type of `java.util.List[File]`. In the event that the user has selected 0 files (or the system toolkit returns null), the method will return null implicitly cast as `java.util.List[String]`. This will happen during runtime when the user is presented with a multiple file selection dialog and chooses the `Cancel` option (documentation for `com.sun.glass.ui.CommonDialogs.FileChooserResult` verifies that an empty list signifies cancellation). When said implicitly cast null value reaches the caller in scalafx, an implicit conversion is made from `java.util.List[java.io.File]` to `scala.collection.Seq[java.io.File]`. Because the implicit conversion process involves performing operations on the underlying collection, a `NullPointerException` is thrown originating in the `scala.collection` API, which travels back up to the caller of `scalafx.stage.FileChooser.showOpenMultipleDialog`. Due to the nature of `NullPointerException`, it makes it hard to programmatically determine whether or not this error was caused by the selection of `Cancel`. This makes it exceptionally hard to develop a case to handle scenarios where you must perform an action after the potential cancellation has occurred, as the only way to do so is to place the file selection dialog call inside of a try/catch block with a blanket catch for `NullPointerException`.

In the interest of maintaining method signature, I would suggest one of the following solutions:

1. Perform the conversion manually, checking for a null value and returning null without proceeding.
2. Perform the conversion manually, checking for a null value and returning an empty `Seq[File]`
3. Allow the implicit conversion, but catch the exception, and return null
4. Allow the implicit conversion, but catch the exception, and return an empty `Seq[File]`

Solution one offers what a good solution, as it retains signature, but returns null as opposed to halting the thread. New implementers may use Option.apply(Any) to wrap the return value and deal with the problem in a sane manner.

Solution two offers also offers a good solution, as it retains signature, and returns an empty `Seq` of the expected type. This means that any functions called against the sequence, most likely iterators, will act upon no file as opposed to resulting in a `NullPointerException`.

I am aware that this issue is more of a fault of scala's `JavaConversions` bundle than scalafx, and I plan to report this to the scala bug tracker as well.

[This Gist](https://gist.github.com/RomanHargrave/72d5bd40688d441d92c1) demonstrates some scalafx-agnostic code that will generate a similar exception.

**Comment by RomanHargrave** [comment]
This was found to occur in SFX-2. The 8._ branch has not been tested.

**Comment by jpsacha** [comment]
Fixed using option 1 at best aligns with conventions currently used in ScalaFX (return null is JavaFX documents returning null).

**Comment by RomanHargrave** [comment]
Thanks for the quick fix! For reference purposes, [SI-9113](https://issues.scala-lang.org/browse/SI-9113), the related language issue, now exists.
