### ISSUE TITLE
ListView is missing setVisibleRowCount(Int)

### ISSUE THREAD

**Issue by takiri** [scalafx/scalafx#183]
Hi,
I think ListView should be provided a 'visibleRowCount' property, same as in ComboBox.
I have looked for a solution but as far as I can see, there are only tricky workarounds and a lot of demands.

Thanks!

**Comment by scalasolist** [comment]
How does this is implemented in pure javafx?

**Comment by takiri** [comment]
I don't think this is implemented for ListView in JavaFX neither. I only thought it could be an interesting feature. I suggested 'visibleRowCount' as a name, based on the fact that the ComboBox does have this feature and uses a ListView as a method of display.

**Comment by jpsacha** [comment]
`visibleRowCount` in `ComboBox` controls display of a popup specific to `ComboBox`. There is no corresponding functionality in `ListView` (no popups), number of displayed rows depends on their size and layout. Those are different mechanisms.
