### ISSUE TITLE
MenuTest and MenuBarTest don't work

### ISSUE THREAD

**Issue by gvidaver** [scalafx/scalafx#187]
Tried the scalafx.controls.MenuTest and scalafx.controls.MenuBarTest and I see blank screens.
![screen shot 2015-04-07 at 4 14 39 pm](https://cloud.githubusercontent.com/assets/4854720/7032531/407e3f2a-dd41-11e4-8b52-532f536c31ca.png)

**Comment by jpsacha** [comment]
This not a bug in ScalaFX. It is the default JavaFX behaviour. On Mac menus by default show in top bar, so you do not see them in the window. If you want to show them in your window you will need to set `useSystemMenuBar` to `false`. For instance:

``` scala
object MenuBarTest extends JFXApp {

  stage = new PrimaryStage {
    title = "MenuBar Test"
    width = 300
    height = 225
    scene = new Scene {
      fill = Color.LightGray
      root = new BorderPane {
        top = new MenuBar {
          useSystemMenuBar = true
          minWidth = 100
          menus.add(new Menu("test"))
          val os = System.getProperty ("os.name")
          if (os != null && os.startsWith ("Mac"))
            useSystemMenuBar = false
        }
      }
    }
  }
}
```
