### ISSUE TITLE
TableView.columnResizePolicy does not accept CONSTRAINED_RESIZE_POLICY

### ISSUE THREAD

**Issue by scalasolist** [scalafx/scalafx#189]
TableView has a scalafx wrapper. But javafx counterpart has static member CONSTRAINED_RESIZE_POLICY which is missing in the corresponding scalafx companion object.

So it is impossible to assign `javafx.TableView.CONSTRAINED_RESIZE_POLICY` to the `scalafx.TableView.columnResizePolicy`

```
[error]  type mismatch:
[error]  found   : javafx.util.Callback[javafx.scene.control.TableView.ResizeFeatures[_],java.lang.Boolean]
[error]  required: scalafx.scene.control.TableView.ResizeFeatures[GroupForm.this.Elem] => scala.Boolean
```

There is no explicit `CONSTRAINED_RESIZE_POLICY` declaration inside the TableView object. And there is no implicit transformation for the `Callback` type

**Comment by jpsacha** [comment]
I added support for predefined resize policies to the most recent `8.0.40-R9-NAPSHOT`. You can do it now using code like this:

```scala
table1.columnResizePolicy = TableView.ConstrainedResizePolicy
```

There is also a complete example in the new [TableViewColumnResizePolicyDemo](https://github.com/scalafx/scalafx/blob/master/scalafx-demos/src/main/scala/scalafx/controls/tableview/TableViewColumnResizePolicyDemo.scala).
