### ISSUE TITLE
Convenience methods for clipboard assignment don't work

### ISSUE THREAD

**Issue by benedictleejh** [scalafx/scalafx#190]
When attempting to assign to the clipboard, using the convenience methods result in a compile error. The test code is included below.

```scala
object Test {
  val clipboard = new Clipboard(Clipboard.systemClipboard)
  
  val cnt = new ClipboardContent()
  cnt.putString("Hello")
  
  clipboard.content = cnt //compile error: Reassignment to val
}
```

I'm on ScalaFX 8.0.40-R8, Scala 2.11.6, and JDK 8u45

**Comment by jpsacha** [comment]
JavaFX `getContent(...)` takes a parameter. Scala `content_=(...)` requires parameter-less `content`.

The only fix I see is to use `getContent(...)`/`setContent(...)`, adding wrapper that use ScalaFX types. So it would be:
``` scala
  val cnt = new ClipboardContent()
  cnt.putString("Hello")
  clipboard.setContent(cnt)
```

Any suggestions on better way of doing this?

**Comment by benedictleejh** [comment]
While it would break the parallel with JavaFX, a possibility would be for `content` to return the entire `Map` (possibly as `ClipboardContent`), while having a `getContent(...)` to get individual key-value pairs. `getContent` would thus ideally also return an `Option` instead of null where no such element exists. This would allow keeping the convenience method.

**Comment by jpsacha** [comment]
Would you like to implement it and submit pull request (on master branch)?

**Comment by benedictleejh** [comment]
Alright, I'll give it a go. I'll see if I can't get something out over the weekend.
