### ISSUE TITLE
Calling scalafx.scene.Node.localToParentTransform / localToSceneTransform results in StackOverflow exception

### ISSUE THREAD

**Issue by albel727** [scalafx/scalafx#205]
The problem stems from their definition, e.g.
```
  def localToSceneTransform: Transform = delegate.localToSceneTransform
```

But the javafx.scene.Node delegate **doesn't have** the method localToSceneTransform(). It has **get**LocalToSceneTransform(). Since this is the case, what scala compiler does instead is applying the implicit conversion of jfxs.Node into scalafx.scene.Node... Yes! Right back into the same Node class we're starting from!... And calls its localToSceneTransform, i.e. the very same function we're in already.

Solution: change definitions to
```
  def localToSceneTransform: Transform = delegate.getLocalToSceneTransform
  def localToParentTransform: Transform = delegate.getLocalToParentTransform
```
I'd also advise to investigate whether implicit conversions produced similar recursion bugs in other places.

**Comment by jpsacha** [comment]
I create for IDEA Live-Plugin to detect recursive methods:
https://gist.github.com/jpsacha/9864e30dc884683bee18

I will try to find other instances of infinite recursion, before closing this issue.

**Comment by jpsacha** [comment]
All infinite recursion calls should be corrected now.
