### ISSUE TITLE
ChartIncludes is missing?

### ISSUE THREAD

**Issue by IntelligyScience** [scalafx/scalafx#207]
I got this error:

Error:scalac: missing or invalid dependency detected while loading class file 'ChartIncludes.class'.
Could not access type SortingPolicy in object javafx.scene.chart.LineChart,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'ChartIncludes.class' was compiled against an incompatible version of javafx.scene.chart.LineChart.

If i roll back to 
libraryDependencies += "org.scalafx" % "scalafx_2.11" % "8.0.20-R6"

this errors does not appear!

Someone knows a solution for this issue?

**Comment by jpsacha** [comment]
You need to match ScalaFX version to Java version. `SortingPolicy` was introduced in Java 8u40. You will get a missing dependency if you try to call it from older version of Java.

**Comment by IntelligyScience** [comment]
I set up all to java 1.8.51 

But I get the same error in intelliJ.
I have this error only on mac.

**Comment by IntelligyScience** [comment]
A deep setting in IntelliJ used an old 1.8.20 version. That was the reason.
Thanks for your time.

**Comment by mimien** [comment]
Could you tell me the reason please?
I have exactly the same problem

**Comment by jpsacha** [comment]
You need to make sure that proper version of JDK is used for 
compilation. YOu can do that by selecting JDK for the project in IDEA 
options.

Jarek

**Comment by richard-jepps** [comment]
If you use the Scala compile server then its JDK will need to be configured in addition to the main project JDK.
