### ISSUE TITLE
Why is `stage.fullScreen` read-only?

### ISSUE THREAD

**Issue by kindlychung** [scalafx/scalafx#211]
Here is an example from Pro ScalaFx:

```
  stage.resizable = false
  stage.resizable <==> checkBoxResizable.selected
  checkBoxFullScreen.onAction = handle {
    stage.fullScreen = checkBoxFullScreen.selected()
  }
```

Intuitively we should be able to do this:

```
  stage.fullScreen <==> checkBoxFullScreen.selected
```

But instead the symbol `<==>` cannot be resolved in this case. Intellij shows that `stage.fullScreen` is of type `ReadOnlyBooleanProperty`, while `stage.resizable` is of type `BooleanProperty`.

**Comment by jpsacha** [comment]
ScalaFX follows JavaFX API. `fullScreen` is defined as ReadOnlyBooleanProperty [there](https://docs.oracle.com/javase/8/javafx/api/javafx/stage/Stage.html#fullScreenProperty).
