### ISSUE TITLE
Missing access methods in JFXApp

### ISSUE THREAD

**Issue by benedictleejh** [scalafx/scalafx#218]
In JavaFX, when extending the abstract class `Application`, the user has access to the following methods that have no equivalent in ScalaFX:

```java
HostServices getHostServices()
static String getUserAgentStylesheet()
static void setUserAgentStylesheet(String url)
```

`HostServices` provides a bunch of useful things like "code base and document base for an Application, show a web page in a browser, and communicate with the enclosing web page using JavaScript if the Application is running in a browser" (quoted from https://docs.oracle.com/javase/8/javafx/api/javafx/application/HostServices.html).

The user agent stylesheet allows the user to set up a quick way to theme a whole JavaFX application without too much trouble using CSS. I understand that there are classes that expose a user agent stylesheet method, if those are equivalent to the application-level user agent stylesheet, please disregard the relevant methods.

I'm not sure how difficult it would be to incorporate these methods in `JFXApp` given the indirect call to `javafx.application.Application`, but a quick stopgap measure would be to expose the underlying JavaFX `Application`, so that we can have access to these methods.

**Comment by jpsacha** [comment]
`getUserAgentStylesheet`/`setUserAgentStylesheet` are static so require minimal changes. 

`getHostServices` will require reference to running JavaFX `Application` it can be done through `scalafx.application.AppHelper`
