### ISSUE TITLE
Documentation should include installation instructions

### ISSUE THREAD

**Issue by simsong** [scalafx/scalafx#223]
The scalafx documentation should explain how the software is installed.

**Comment by jpsacha** [comment]
ScalaFX is a library. You need to add dependency on ScalaFX in your project. The details depend on what IDE and what build system you are using. Instructions for using it SBT/IntelliJ IDEA are on the [front page](https://github.com/scalafx/scalafx) on this repository. Additional details are in the [Quick Start Guide](http://www.scalafx.org/docs/quickstart/). Did you try those?

**Comment by simsong** [comment]
I suppose that I'm used to a build system that handles libraries in a consistent manner. Sorry for the confusion.
