### ISSUE TITLE
Add `apply` method to the companion objects

### ISSUE THREAD

**Issue by tomoki** [scalafx/scalafx#230]
Hi. Thanks for great library!

I would suggest adding `apply` method to the companion objects like `object VBox`.
This will save you from writing many `new`s, and it make ScalaFX similer to Standard library.

Current ScalaFX requires us writing many `new`s and
I think it is a little different from Scala standard library ways.
For example, here is a small "HelloWorld" program:

``` scala
import scalafx.application.JFXApp
import scalafx.application.JFXApp.PrimaryStage
import scalafx.scene.Scene
import scalafx.scene.text.Text
import scalafx.scene.layout.VBox

object HelloWorld extends JFXApp {
  stage = new PrimaryStage {
    title = "Hello"
    scene = new Scene {
      root = new VBox (
        new Text("Hello"),
        new Text("World"),
        new Text("!")
      )
    }
  }
}
```

In Scala standard library, collections like `Seq` have companion objects which contains `apply` method, so we can define collections much easier.

``` scala
Seq(1, 2, 3)
```

If we add `apply` methods to the companion objects, `Hello World` program can be rewritten to:

``` scala
import scalafx.application.JFXApp
import scalafx.application.JFXApp.PrimaryStage
import scalafx.scene.Scene
import scalafx.scene.text.Text
import scalafx.scene.layout.VBox

object HelloWorld extends JFXApp {
  stage = new PrimaryStage {
    title = "Hello"
    scene = new Scene {
      root = VBox (
        Text("Hello"),
        Text("World"),
        Text("!")
      )
    }
  }
}
```

I think it is much easier than current ScalaFX program.
I also guess, this will not go well all the time.
For example, I don't know how to implement `apply` method for `object PrimaryStage`.
How do you think?

Note:
I checked the design of [Scala Swing](https://github.com/scala/scala-swing/blob/2.0.x/docs/SIP-8.md), and I found that is similer to ScalaFX.
One of the examples is following:

``` scala
import swing._
object HelloWorld extends SimpleSwingApplication {
  def top = new MainFrame {
    title = "Hello, World!"
    contents = new Button {
      text = "Click Me!"
    }
  }
}
```

[The design](http://www.scala-lang.org/old/sites/default/files/sids/imaier/Mon,%202009-11-02,%2008:55/scala-swing-design.pdf) also suggests:

> As it is very common for buttons to have actions, there is a convenience factory method in
> companion object Button . The following is equivalent to the previous example.
> val button = Button("Click me") {
>   println("Someone executed clicked button " + this)
> }

**Comment by s-bernard** [comment]
I think this issue can be closed as Scala 3 provided this feature by default, alas not for anonymous classes which would have been the most interesting case.

**Comment by jpsacha** [comment]
Yes, Scala 3 "resolves" this issue for "direct" instances. For anonymous classes we still need new, I do not see easy way around it.

For the reference here is scala version of the sample:

```scala
import scalafx.application.JFXApp3
import scalafx.application.JFXApp3.PrimaryStage
import scalafx.scene.Scene
import scalafx.scene.layout.VBox
import scalafx.scene.text.Text

object HelloWorld extends JFXApp3:

  override def start(): Unit =
    stage = new PrimaryStage:
      title = "Hello"
      scene = new Scene:
        root = new VBox(
          Text("Hello"),
          Text("World"),
          Text("!")
        )
```
