### ISSUE TITLE
Problem with StringProperty.concat

### ISSUE THREAD

**Issue by JohannesOehm** [scalafx/scalafx#233]
Using `MyStringProperty.concat(" with some constant string ")` works as expected, but `MyStringProperty.concat(anotherStringProperty)` concats MyStringProperty with "[SFX]StringProperty [bean:..., name: propertyname, value: stringvalue]". Users have to use `MyStringProperty.concat(anotherStringProperty.delegate)`. Please fix!

**Comment by jpsacha** [comment]
Note that in ScalaFX you can concatenate string properties using overloaded `+` operator, for instance:
```scalafx
stringProperty <== stringProperty2 + " " + stringProperty3
```
