### ISSUE TITLE
Add an example of a Gradle project that is using ScalaFX 

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#238]
Something simple, like [scalafx-hello-world](https://github.com/scalafx/scalafx-hello-world), that is using Gradle.

**Comment by rajmahendra** [comment]
Not only  gradle we can have other build tool as well   like

inside scalafx-hello-word  we can have
sbt-hello-world
gradle-hello-world
maven-hello-world
cbg
sbuild ....
.....

**Comment by jpsacha** [comment]
To simplify maintenance ScalaFX project will focus on SBT build configuration.
