### ISSUE TITLE
Text.strikethrough_=(v: Boolean) doesn't work.

### ISSUE THREAD

**Issue by MamoruAsagami** [scalafx/scalafx#240]
The following code gets infinite exceptions at at scalafx.scene.text.Text.strikethrough_$eq (Text.scala:104).
    new Text("hello, world") {
      strikethrough = true  // This line causes  infinite exceptions
    }

Text.scala has this.

103  def strikethrough_=(v: Boolean) {
104    strikethrough = v
105  }

Maybe, line 104 should be like as follows;

104    strikethrough() = v

**Comment by jpsacha** [comment]
It was a bug. Your suggestion for fixing was correct. It is fixed now. Thanks.
