### ISSUE TITLE
java 1.8.40 requirement

### ISSUE THREAD

**Issue by piotrm0** [scalafx/scalafx#248]
I noticed that the version of scalafx mentioned in the README.md (8.0.102-R11) requires at least java 1.8.40 with earlier versions having a problem due to missing classes such as `javafx.scene.control.TextFormatter` .

Is there a way that a java version requirement can be imposed before scalafx can be used in an sbt project? The errors presented are not informative. When trying to sbt compile a project that includes 8.0.102-R11 but has java earlier than 1.8.40, the error given looks like this :

```
[error] missing or invalid dependency detected while loading class file 'ControlIncludes.class'.
[error] Could not access type Change in value javafx.scene.control.TextFormatter,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'ControlIncludes.class' was compiled against an incompatible version of javafx.scene.control.TextFormatter.
```

**Comment by jpsacha** [comment]
You can check some suggestions here:
http://stackoverflow.com/questions/19208942/enforcing-java-version-for-scala-project-in-sbt

**Comment by piotrm0** [comment]
Was that something that can be applied to the scalafx project itself so that anyone who uses scalafx will be warned of this instead of getting the cryptic error I posted above? Alternatively (or in addition to), can the README in the project be changed to reflect the requirement?

**Comment by jpsacha** [comment]
There is no explicit initialization method in ScalaFX  (neither in JavaFX), so it is difficult to make the check universal. Maybe in some kind of check in JFXApp, since it is commonly used in ScalaFX applications.

I am open to suggestion.

**Comment by jpsacha** [comment]
As there no suggestions how to fix it and this not an issue with ScalaFX I am closing this issue.
