### ISSUE TITLE
Add ScalaFX to Scala Community builds

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#249]
[Scala Community builds](https://github.com/scala/community-builds) test new Scala builds against open source projects. 
From the project [README](https://github.com/scala/community-builds): "The main goal [of the Scala Community builds] is to guard against regressions in new versions of Scala (language, standard library, and modules). It's also a service to the open source community, providing early notice of issues and incompatibilities."

**Comment by jpsacha** [comment]
Submitted initial PR https://github.com/scala/community-builds/pull/376

**Comment by jpsacha** [comment]
This may need to be revisited for building with Java 11 where JavaFX is an external dependency.

**Comment by rom1dep** [comment]
From my preliminary testing, it's enough to add openjfx (with the proper classifier) in the list of sbt's dependencies for runing against Java11: https://www.reddit.com/r/scala/comments/9fbzbk/build_file_snippet_for_using_javafx_with_java_11/

Hopefully, ScalaFX's build.sbt won't need much change to reflect that.

**Comment by jpsacha** [comment]
@rom1dep Java 11 actually makes it simpler to support Scala Community Build. However, currently some ScalaFX tests fail with JavaFX 11 (as well as 10 and 9). Those needs to be addressed.  Many are resolved by your PR #279. Once all the test pass, we can bet back to Scala Community Build. If you would like to lead that, I will appreciate.

**Comment by jpsacha** [comment]
Made new request for inclusion in Scala Community Builds with this PR: https://github.com/scala/community-build/pull/1174

**Comment by jpsacha** [comment]
ScalaFX for Scala 2.13 is not part of Scala Community build. PR scala/community-build#1174 was merged, though since that build do not support xvfb no test are running, only compilation.
