### ISSUE TITLE
Change custom `cellFactory` assignment methods to help in correct implementation that avoids artifacts

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#256]
JavaFX requires that custom cell factories are implemented in such a way that `javafx.scene.control.Cell[T]#updateItem(T item, boolean empty)` is implemented correctly. Quite from [JavaFX documentation for `updateItem`](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Cell.html#updateItem-T-boolean-]): 

> It is **very important** that subclasses of Cell override the `updateItem` method properly, as failure to do so will lead to issues such as blank cells or cells with unexpected content appearing within them.

Current implementation of helper `cellFactory` assignment is not suitable to handle that. Consider  `TreeCell#cellFactory_=(v: (TreeView[T] => TreeCell[T]))`. Current suggestions is to use it like this:

```scala
cellFactory = (v: TreeView[Person]) => new TreeCell[Person] {
  treeItem.onChange { (_, _, p) =>
    text = if (p != null) p.value().firstName + " " + p.value().lastName else null
    graphic = null
  }
}
```
Above implementation will results in rendering artifacts as empty cells cannot be handled correctly, the `empty` flag is not available. The proper way would be to extends 'javafx.scene.control.Cell':
```scala
cellFactory = _ =>
  new javafx.scene.control.TreeCell[Person] {

  // We are deriving from JavaFX, for easier use add ScalaFX wrapper for  `this`
  val self: TreeCell[Person] = this

  override def updateItem(item: Person, empty: Boolean): Unit = {
     super.updateItem(item, empty)
     self.graphic = null
     self.text =
       if (empty) 
         null
       else item match {
         case p: Person => p.firstName + " " + p.lastName
         case null => null
       }
   }
 }
```
This is a lot of boilerplate code. There should be a helper `cellFactory` assignment that would promote ability to write correct code. Mot of the boilerplate would be generated automatically, user would only handle rendering and be provided with `empty` flag. Consider assignment with signature:

```scala
def cellFactory_=(u: ((TreeCell[T], T, Boolean) => Unit))
```

It would be used like this:
```scala
        cellFactory = (treeCell, item, empty) => {
          treeCell.graphic = null
          treeCell.text =
            if (empty)
              null
            else
              item match {
                case p: Person => item.firstName + " " + item.lastName
                case null => null
              }
        }
```

Maybe it should be even simpler. Code for resetting `graphic` and `text` when item is `null` or empty would be generated automatically. A cell factory would only handle non-null items and non-empty cells:
```scala
        cellFactory = (treeCell, item) => {
          treeCell.text =  item.firstName + " " + item.lastName
        }
```

This would be for all classes that have cell factories, not only `TreeView`.

**Comment by objektwerks** [comment]
I've used the scalafx.org table view custom cell docs before with great success! Thanks!

But I struggled for the past hour with a combo box and list view custom cell. So I look forward to your new cell factory masterpiece! Cheers! :)

**Comment by DavidGoodenough** [comment]
There would appear to be a regression in ScalaFx 15, assigning a function which returns a Java TreeTableCell no longer works, it get flagged as:-

overloaded method cellFactory_= with alternatives:\n  (callback: javafx.util.Callback[javafx.scene.control.TreeTableColumn[R,String],javafx.scene.control.TreeTableCell[R,String]])Unit <and>\n  (f: scalafx.scene.control.TreeTableColumn[R,String] => scalafx.scene.control.TreeTableCell[R,String])Unit\n cannot be applied to (scalafx.scene.control.TreeTableColumn[R,String] => javafx.scene.control.TreeTableCell[R,String])

The assignment worked in ScalaFx 14, but if I change to 15 it stops working.  Changing to a scalafx.s.c.TreeTableCell does not help, as it does not have updateItem method.

So the change requested by this issue just got more urgent.

**Comment by jpsacha** [comment]
@DavidGoodenough an easy to reproduce example of the issue will be helpful

**Comment by DavidGoodenough** [comment]
I notice in the bottom of javafx/scene/control/Cell.scala there is a comment about updateItem.  Would a possible approach be to provide a default implementation (which did nothing) in the scala code, and in the declaration of the delegate override the java updateItem and have it call the scala method?  This would need to be done for all the ...Cell.scala classes.

**Comment by jpsacha** [comment]
@DavidGoodenough  in general, ScalaFX delegates to JavaFX, but does not extend JavaFX classes. For `updateItem` to work correctly a class needs to extend respective JavaFX class, like here:
```Scala
cellFactory = _ =>
  new javafx.scene.control.TreeCell[Person] {
  override def updateItem(item: Person, empty: Boolean): Unit = ...
 }
```
I do not see how to do it in current ScalaFX code in a clean way. If you can please provide some example what you mean.

There is an alternate approach, proposed in the description of the issue above, that does not involve overriding `updateItem`.
 Here relatively elaborated cell factory that creates a colored text. [ColorCharactersInTableView](https://github.com/scalafx/ScalaFX-Tutorials/blob/cee2e4f1831693df7fb4bc1b6e3ae5007a80628a/cell_factories/src/main/scala/cell_factories/ColorCharactersInTableView.scala#L44) is using `updateItem` JavaFX-way, and the same thing using only ScalaFX approach proposed: [ColorCharactersInTableView2](https://github.com/scalafx/ScalaFX-Tutorials/blob/cee2e4f1831693df7fb4bc1b6e3ae5007a80628a/cell_factories/src/main/scala/cell_factories/ColorCharactersInTableView2.scala#L41)

**Comment by DavidGoodenough** [comment]
And your suggestion could be done simply by removing the scalafx version of TreeCell and defining cellFactory to require a lambda that returns a jfsc.TreeCell, and then the override would work just as you say.  Effectively the current scalafx TreeCell (or whateverCell) is useless as you can not override the methods that are designed to be overriden.  The TreeCell any IDE would prompt you to include would be the javafx one (their being no other in this senario) and it would look just as you have shown, I am not sure I understand why this is "unclean" and it exactly mirrors all the javafx examples, just written in scala syntax.

**Comment by jpsacha** [comment]
I think I do not fully understand how you are proposing to resolve the issue. TreeCell, as are the other ScalaFX classes, do not inherit from JavaFX classe. This is a patterns throughout the whole ScalaFX code base. The main purpose of ScalaFX TreeCell class is to have simpler access to properties (disclosureNode, treeItem, treeView), so it cannot really be removed. That would break general ScalaFX pattern. 

What am I trying to say is that we can provide a mechanism to create custom cell factories without extending JavaFX classes at the user end. It is always possible (you can always mix use of JavaFX and ScalaFX as shown in the [ColorCharactersInTableView](https://github.com/scalafx/ScalaFX-Tutorials/blob/cee2e4f1831693df7fb4bc1b6e3ae5007a80628a/cell_factories/src/main/scala/cell_factories/ColorCharactersInTableView.scala#L44) example), but for many cases not necessary. The other aspect of this issue is that when extending TreeCell updateItem  it is easy to miss some boilerplate that can result in incorrectly rendered UI (as discussed at the top, when you need to remember to set `graphics` or `text` to `null`).

This issue is open for a while since practical implementation, that is generic, easy to use, and fits with the rest of the usage patterns of ScalaFX, is not necessary obvious (at least to me). The examples above give some use cases. You likely have some additional ones that needs to be considered too.

I do not really understand what you are proposing, my bad. Can you provide some demo implementation of your approach how to improve ScalaFX custom cell factory creation, say for the TreeView/TreeColumn/TreeCell example?
