### ISSUE TITLE
Adding Typelevel CoC in ScalaFX 

### ISSUE THREAD

**Issue by rajmahendra** [scalafx/scalafx#258]
As part of adopting Typelevel CoC following line need to be added to ScalaFX repo and Website : 

People are expected to follow the [Typelevel Code of Conduct](http://typelevel.org/conduct.html) in mailing-list, issue discussions, Gitter chat ( [![Join the chat at https://gitter.im/scalafx/scalafx](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/scalafx/scalafx?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) ) rooms or in any ScalaFX meetups.

**Comment by jpsacha** [comment]
I added note to the [scalafx.org](http://scalafx.org/) front page and the mailing lists.
