### ISSUE TITLE
Value members in object BackgroundPosition have the wrong type?

### ISSUE THREAD

**Issue by Julien-Lopez** [scalafx/scalafx#271]
Hello! Thank you for this library!

I noticed that `BackgroundPosition.Center` and `BackgroundPosition.Default` have the type `javafx.scene.layout.BackgroundPosition` instead of `scalafx.scene.layout.BackgroundPosition`.

Is this an error? If so, can you please fix it so I don't have to write a silly `new BackgroundPosition(BackgroundPosition.Default)`? ;-)

Thanks!

**Comment by jpsacha** [comment]
Thanks for pointing this out.
