### ISSUE TITLE
Help sbt assembly to include all necessary files

### ISSUE THREAD

**Issue by norbusan** [scalafx/scalafx#272]
Dear all,
there seems to be a problem with sbt assembly to include all necessary files into a fat jar, see https://stackoverflow.com/questions/16868446

Maybe something can be done from the ScalaFX side to enhance this experience?

I am currently building an application based on ScalaFX, but deployment via a single self-contained jar is at the moment impossible for me, due to the above problem.

Any chance or suggestion from ScalaFX developers on how to create fat jars that do not require JavaFX being installed on the host computer?

Thanks

Norbert

**Comment by objektwerks** [comment]
Hey, Norbet

You might consider looking into these 2 packaging tools:

1. SBT Native Packager - http://www.scala-sbt.org/sbt-native-packager/index.html <http://www.scala-sbt.org/sbt-native-packager/index.html>
2. JavaFx Packager Tool - http://docs.oracle.com/javafx/2/deployment/packager.htm <http://docs.oracle.com/javafx/2/deployment/packager.htm>

Both allow you to package a target JRE with your app and dependencies.

Cheers, Mike

**Comment by norbusan** [comment]
Thanks for the feedback, but I realized the my issue was bogus right from the beginning. JavaFX ships shared objects, so there is no way to package a self-contained jar which only needs plain Java. Should have realized this earlier.
Your suggestions are interesting in the sense that one can include even more stuff, but I doubt that shipping .so/.dll will work on different systems.

Sorry for the noise and thanks again.

**Comment by objektwerks** [comment]
FWIW, those app packaging toolkits can target all operating systems! So, indeed, it does make a ton of sense to package a JavaFX/ScalaFX app in such a manner — creating a tailor-made install package for each OS.

**Comment by norbusan** [comment]
Well, I am not sure whether this will work inpractice, having fought with distributing shared objects. In thi sense Windows DLL are better because they are more or less unchanged, while the .so files are not easily distributable between systems (different libc,different gcc, ...).
So yes, the tools are fine but I am not sure whether they manage to produce something useable when including JavaFX's .jar/.so files.
