### ISSUE TITLE
scalaFX.jar

### ISSUE THREAD

**Issue by DimitryBur** [scalafx/scalafx#275]

**Comment by jpsacha** [comment]
You have an example of a complete working project here: [scalafx-hello-world](https://github.com/scalafx/scalafx-hello-world).

**Comment by DimitryBur** [comment]
My example run too, but ат startup standalone jar file error:""Error: A JNI error has occured, please check your installation and try again."

**Comment by jpsacha** [comment]
The issue does not explain what the problem is.
