### ISSUE TITLE
Example on website uses Scene.content instead of Scene.root

### ISSUE THREAD

**Issue by ziggystar** [scalafx/scalafx#276]
This has cost me one hour of searching, until I found an answer on [StackOverflow](https://stackoverflow.com/questions/36023189/scalafx-javafx-stage-content-does-not-resize-on-window-resize).

The example on the very first page of your website states:

```
import scalafx.Includes._
import scalafx.application.JFXApp
import scalafx.scene.Scene
import scalafx.scene.paint.Color._
import scalafx.scene.shape.Rectangle

object HelloStageDemo extends JFXApp {
  stage = new JFXApp.PrimaryStage {
    title.value = "Hello Stage"
    width = 600
    height = 450
    scene = new Scene {
      fill = LightGreen
      content = new Rectangle {
        x = 25
        y = 40
        width = 100
        height = 100
        fill <== when(hover) choose Green otherwise Red
      }
    }
  }
}
```

It uses `content =` instead of `root =`. This appears to be wrong, as resizing the window will not resize the GUI if using `content`.

**Comment by jpsacha** [comment]
Thanks for pointing this out. 
Can you submit PR for this? 
The source is in [scalafx.github.io](https://github.com/scalafx/scalafx.github.io) project in [index.md](https://github.com/scalafx/scalafx.github.io/blob/master/index.md).
Thanks.

**Comment by jpsacha** [comment]
Fixed

**Comment by jpsacha** [comment]
In this case the Rectangle is not intended to resize (notice it has fixed width and height specified). It also cannot be directly assigned to root, you will need to add additional container for it.
