### ISSUE TITLE
Java 9 Support

### ISSUE THREAD

**Issue by sfxcode** [scalafx/scalafx#278]
Add Java 9 support.

**Comment by jpsacha** [comment]
Help is really appreciated with adding Java 9 Support.

**Comment by rom1dep** [comment]
Still using ScalaFX :)
What would the support for Java9(/10, actually) look like? Is there a log of the API changes somewhere to help getting the job started? How about the changes underneath?

**Comment by jpsacha** [comment]
I will see it as a two step process. First, make corrections so current code builds on Java 10. Second, add missing wrappers. In the past, I used a JAR comparison tool to see what changed in JavaFX between releases. I am not sure if there is something that will work with the new module systems to automatically list the differences between 8 and 9/10.

**Comment by jpsacha** [comment]
I created a branch SFX-10 for work on port for Java 10. I did some minimal changes required to build on Java 10. Many test pass, some fail. I tried a couple of demos, all were working.

I will not have much time to work on it. Please feel free to contribute toward JavaFX 10 support.

**Comment by rom1dep** [comment]
Ok, so, if I understand the gist of it, the lowest hanging fruit is to run the test suite and implement any missing property.
I did just that for `Spinner`:
https://github.com/rom1dep/scalafx/commit/ac34e13ce7699ce0473f074adbe13ee3c83ebbe8

There are approximately 21 such properties. Any early feedback/warning/peculiarity I should be aware of before proceeding? (code formatting preference? From a quick look, there don't seem to be a particular order for the methods, so I guess it doesn't matter?)

**Comment by jpsacha** [comment]
All the test are now passing on SFX-10 branch, so I am closing this issue. Open new issues, if needed, for new class wrappers.
