### ISSUE TITLE
Bindings inappropriately garbage-collected

### ISSUE THREAD

**Issue by dmurvihill** [scalafx/scalafx#280]
I want my Stage to pass a property to two children: a button that fetches some data and stores the result in the property, and a pane that visualizes the result.

Here is a MWE:

```scala
package com.voatz

import scalafx.Includes._
import scalafx.application.JFXApp
import scalafx.application.JFXApp.PrimaryStage
import scalafx.beans.binding.Bindings
import scalafx.beans.property.{BooleanProperty, ObjectProperty}
import scalafx.scene.control.Button
import scalafx.scene.layout._
import scalafx.scene.paint.Color
import scalafx.scene.shape.{Rectangle, Shape}
import scalafx.scene.{Node, Scene}

object BindingsBug extends JFXApp {
  stage = new PrimaryStage {
    scene = new Scene {
      content = new HBox {
        val shouldDrawBox: BooleanProperty = BooleanProperty(false)
        val vPane = new VisualPane(shouldDrawBox)
        shouldDrawBox.onChange((_, _, newValue) => println(s"Setting shouldDrawBox = $newValue"))
        children = Seq(new RekogButton(shouldDrawBox, vPane), vPane)
      }
    }
  }

  stage.show
}

class RekogButton(shouldDrawBox: BooleanProperty,
                  vPane: VisualPane) extends Button("Bug!") {
  onAction = handle {
    // UNCOMMENT TO GET WORKING
    // val dontGcMeBro = vPane
    shouldDrawBox() = true
  }
}


class VisualPane(shouldDrawBox: BooleanProperty) extends AnchorPane {

  private val outlines = ObjectProperty[Option[Shape]](None)
  outlines <== Bindings.createObjectBinding[Option[Shape]](
    () => {
      val newVal = if(shouldDrawBox()) Some(getRect) else None
      println(s"value for rect: $newVal")
      newVal
    },
    shouldDrawBox
  )

  private val _children = Bindings.createObjectBinding[Seq[Node]](
    () => if (outlines().isDefined) Seq(outlines().get) else Seq.empty, outlines
  )
  children_=(_children.value)
  _children.onChange((_, _, newValue) => children_=(newValue))

  private def getRect: Shape = {
    val polygon = Rectangle(100, 50)
    polygon.setStroke(Color.Black)
    polygon.setFill(Color.Transparent)
    polygon
  }
}

```

Problem is, by the time the "shouldDrawBox" property has been updated, the listener that updates the binding to "outlines" has already been garbage-collected! As a result, the message "setting shouldDrawBox = true" is printed, but the "value for rect" message is never printed, and the rectangle is not drawn.

Sometimes it happens that the garbage collector never runs between initialization of the binding and the time the user clicks the button. In that case it works fine.

I suspected the GC might have mistakenly cleared my binding because it was stored in a ScalaFX subclass rather than the delegate, but it seems to me that the reference from 'outlines' in the vPane should count as a strong reference. There may be something I'm missing about how garbage collection works.

**Comment by jpsacha** [comment]
I do not see here anything that it would indicate that it is a ScalaFX bug. It is more likely a peculiarity how JavaFX clean bindings and how Scala constructor private values work.
