### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#298]
- [x] JavaFX collection wrappers using new Scala 2.13 collections API
- [x] Correct use of Scala 2.13 collections API
- [x] Some of the test are broken (e.g. AxisSpecs), due to change in ScalaTest API (?)
- [x] Setup Travis CI to test with Scala 2.13

**Comment by jpsacha** [comment]
[scala-collection-compat](https://github.com/scala/scala-collection-compat) should help with converting custom collections to new 2.13 collections API. The ReadMe for the project describes migration tool that may help in converting current ScalaFX code.

**Comment by sarahgerweck** [comment]
Would you release a new build of ScalaFX 8 with Scala 2.13 support? I might help with this, but I'm reluctant to add a Java 12 requirement for my most important use case. I'm more likely to proceed with a private fork if ScalaFX 8 + Scala 2.13 is not coming.

**Comment by jpsacha** [comment]
@sarahgerweck ScalaFX 8 and Scala 2.12 are two separate issues. 

ScalaFX 8 (Scala 2.12, 2.11) build is relatively easy, it just needs help with preparing and testing the build with some possible backporting of recent changes from the master branch. If you can do it, I will publish the build.

Support for Scala 2.13 is more difficult. There are very significant changes to the collections library. Significant amount of work is needed to rewrite custom ScalaFX collection to work with Scala 2.13. Help is definitely needed here. After looking at this for a while, I think that the best is to do full clean rewrite of ScalaFX collections implementation using the new Scala 2.13 collections. Suggestions and help with doing this are very welcomed.

**Comment by sarahgerweck** [comment]
@jpsacha I get that they're separate issues, but it appeared from the release history that you may not be issuing more JavaFX 8 builds. I can't make any promises right now, but I _may_ be able to help with the Scala 2.13 port. (I've ported another library and have done some prototyping at what a 2.13 ScalaFX fork might look like, so I have a decent picture of what's required.) I'd probably need a JavaFX 8 build to be released for it to be useful for my use case. (We're getting closer, but we still have a few internal things that don't run correctly on JDK 9 and above.)

If I were to go down the road of a Scala 2.13 port, how confident are you that the existing collections test suites cover the existing functionality well? I'm sure some tweaks would be required, but if there's already a pretty good test suite, that makes this a smaller project than if tests need to be developed from scratch. (It looks like there are reasonably good tests, but I haven't gone through them in detail.)

**Comment by sarahgerweck** [comment]
Oops, sorry I missed your sentence about the JavaFX 8 backport. Ignore the first paragraph above.

**Comment by jpsacha** [comment]
There is a good number of tests for the collections. There are also demo projects, like [ProScalaFX](https://github.com/scalafx/ProScalaFX), that can be used to test.

The bulk of the current collections code would be the same. The inheritance and traits in implementation will need to be changed to match the new design of Scala 2.13 collections. There will need to be some deprecations or removal in the API to match Scala 2.13. By "clean rewrite" above I ment sticking to the new Scala 2.13 philosophy of collections, removing things that do not much.

**Comment by rom1dep** [comment]
@jpsacha `mill scalafx[2.13.0].test` comes all green, what an impressive feat :)

**Comment by jpsacha** [comment]
All things compile and tests are now passing, including Travis CI.

Snapshot release is published as `12.0.2-R18-SNAPSHOT`:
https://oss.sonatype.org/content/repositories/snapshots/org/scalafx/scalafx_2.13/12.0.2-R18-SNAPSHOT/

**Comment by jpsacha** [comment]
Scala 2.13 support is working.
