### ISSUE TITLE
Implement FIXME in scalafx.scene.layout.Border

### ISSUE THREAD

**Issue by Jeansen** [scalafx/scalafx#300]
scalafx.scene.layout.Border ist the only class that still has a FIXME comment. I'd implement it myself, but am too far away from the implementation. I bet it is a minor thing, but resolving it would allow the usage for Border (together with Region) within scalafx.

I'd gladly help with testing!

**Comment by Jeansen** [comment]
Just saw, that it is related to https://github.com/scalafx/scalafx/issues/33

**Comment by jpsacha** [comment]
@Jeansen please take look that new constructors look fine

**Comment by Jeansen** [comment]
Looks fine. Thanks for resolving :+1:
