### ISSUE TITLE
FileChooser extension filter setup

### ISSUE THREAD

**Issue by schrepfler** [scalafx/scalafx#314]
Not sure why but I think the documented way to add extension filters to a FileChooser doesn't work (at least on 2.13) 

```scala
 val fileChooser = new FileChooser {
  title = "Open Resource File"
  extensionFilters ++= Seq(
    new ExtensionFilter("Text Files", "*.txt"),
    new ExtensionFilter("Image Files", Seq("*.png", "*.jpg", "*.gif")),
    new ExtensionFilter("Audio Files", Seq("*.wav", "*.mp3", "*.aac")),
    new ExtensionFilter("All Files", "*.*")
  )
 }
```

so we should probably update the docs to something like
```scala
extensionFilters.addAll(
    new ExtensionFilter("Text Files", "*.txt"),
    new ExtensionFilter("Image Files", Seq("*.png", "*.jpg", "*.gif")),
    new ExtensionFilter("Audio Files", Seq("*.wav", "*.mp3", "*.aac")),
    new ExtensionFilter("All Files", "*.*"))
```

**Comment by Facsimiler** [comment]
I took a quick look at this, and I'm not convinced it's actually incorrect documentation...

`extensionFilters` is a getter method that it implemented as follows:

```scala
/**
   * Gets the extension filters used in the displayed file dialog.
   */
def extensionFilters = delegate.getExtensionFilters
```

where `delegate` is the _JavaFX_ version of `FileChooser`. The `getExentsionFilters` method returns an `ObservableList` of extension filters. So far, so good.

The `++=` method is provided by `ObservableBuffer`, which is the _ScalaFX_ equivalent of `ObservableList`. Consequently, there should be an _implicit conversion_ that converts the latter to the former, and allowing the `++=` method to be applied.

There are many, many, many implicit conversions required to convert between _JavaFX_ and equivalent _ScalaFX_ elements, and so _ScalaFX_ requires that the following import statement be present in every _ScalaFX_ source file:

```scala
import scalafx.Includes._
```

Can you confirm that this import is present when compiling the documented usage?

**Comment by jpsacha** [comment]
Can you explain what documentation you are looking at (file/webpage)?

**Comment by Facsimiler** [comment]
I think it's the [usage example](http://www.scalafx.org/api/8.0/index.html#scalafx.stage.FileChooser) in the API docs.

**Comment by schrepfler** [comment]
You're correct, with the `import scalafx.Includes._` the snippet works. I was looking directly at the source docs for `FileChooser.scala`
https://github.com/scalafx/scalafx/blob/master/scalafx/src/main/scala/scalafx/stage/FileChooser.scala#L89

**Comment by Facsimiler** [comment]
It's a shame we can't make _all_ source files have that import statement by default; I think it's the #1 cause of user problems with _ScalaFX_. :-)

**Comment by jpsacha** [comment]
Yes, missing `import scalafx.Includes._` is frequently a problem. I wish there was some way to resolve this...

I updated the particular documentation location and added test to make sure it works
