### ISSUE TITLE
Application packaging

### ISSUE THREAD

**Issue by schrepfler** [scalafx/scalafx#315]
Can we have some examples how to package ScalaFX apps? Should we build fat jars with assembly or use scala-native-packager with its own conventions?
Is there any thought on jlink and how do we move forward with javafx13 + java module system?

**Comment by jpsacha** [comment]
There is an example. Take a look how [ScalaFX Ensemble](https://github.com/scalafx/scalafx-ensemble) is packaged. It is using [Install4J](https://www.ej-technologies.com/products/install4j/overview.html). There is also an SBT plugin [sbt-install4j](https://github.com/jpsacha/sbt-install4j) that makes the whole process easy in SBT.

Install4J is a great commercial product with nice UI for simple installer creation, but also  highly customizable. It is free for established Open Source projects, see they web page. A free Open Source version was used to packager ScalaFX Ensemble. I use paid version for commercial work for many years.

[jpackage](https://jdk.java.net/jpackage/) was quite a pain to use and at this point is no longer distributed with Java. It is promised to be back in Java 14. It would not be my recommendation, unless it is significantly improved.

**Comment by hohonuuli** [comment]
I've been using jpackage (from JDK 14) for in-house applications for about 6 months now. (I started using the very early versions). It is **much** better than the one that was distributed with Java 8. It's been working great on macOS, and Linux. I haven't tried it on Windows yet.

**Comment by schrepfler** [comment]
Can you share your setup, is it managed via SBT or you invoke it directly?

**Comment by hohonuuli** [comment]
Just a disclaimer that I'm using jpackage with __Java app's__ via gradle and [the badass-jlink-plugin](https://badass-jlink-plugin.beryx.org/releases/latest/); they're not ScalaFX projects. 

I haven't found anything for SBT yet, although I expect that will be add to [sbt-native-packager](https://github.com/sbt/sbt-native-packager) pretty quickly after JDK 14 comes out. For a Scala project, you'll probably need to cobble together a shell script or write a custom SBT task. 

You can see any example project at <https://github.com/mbari-media-management/vars-annotation>

**Comment by schrepfler** [comment]
sbt-native-packager already has something for jlink but it's not working for me, java modules pains. https://www.scala-sbt.org/sbt-native-packager/archetypes/misc_archetypes.html

**Comment by hohonuuli** [comment]
> java module pains.

I feel ya.

A note about jlink: it builds a minimal runtime image with with this layout:

```
.
├── bin
├── conf
├── legal
├── lib
└── release
```

This works if you distribute your app as a zip file and your users are somewhat savvy. If you want to dmg, msi, or deb package then jpackage is what you want.

**Comment by jpsacha** [comment]
Since it is not a ScalaFX code issue, the mailing list or StackOverflow are better places to continue this question.
