### ISSUE TITLE
Update README for Mill

### ISSUE THREAD

**Issue by bbstilson** [scalafx/scalafx#319]
Hey folks. I'm trying out [Mill](http://www.lihaoyi.com/mill/index.html), and it took a bit of digging to figure out how to get ScalaFX working. Would it be alright if I opened a PR to update the README  under the [ScalaFX Dependencies](https://github.com/scalafx/scalafx#scalafx-dependencies) section?

**Comment by rom1dep** [comment]
Can't answer to that,

but I thought that maybe you'd like a pointer to this recent regression in mill that makes things slightly more complicated: https://github.com/lihaoyi/mill/issues/767

**Comment by lefou** [comment]
I'm not involved in this repo in any way, but I think you should just open that PR and link it here. Even if it doesn't get merged, anybody who searches for a solution can read that PR anyway.

**Comment by bbstilson** [comment]
@lefou good point. I opened a PR.
