### ISSUE TITLE
Support Scala 3/dotty

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#322]
Scala 3 (dotty) is planned to be released at the end of 2020.

It should be mostly compatible with Scala 2.13. One of the few exception being `DelayedInit` used to implement `JFXApp`

It should be possible to add cross compilation option for dotty in current build

* [ ] Redesign JavaFX `Application` wrapper class to work well with Scala 3. `DelayedInit` used to implement `JFXApp` cannot be used in Scala 3

**Comment by jpsacha** [comment]
It is possible to run simple ScalaFX applications using 2.13 libraries. See example: https://github.com/scalafx/scalafx-hello-world/tree/Scala3

**Comment by Kalin-Rudnicki** [comment]
@jpsacha I am new to this, and trying out dotty as well. I managed to get the example from the `Scala3` branch running, but when I try and use `JFXApp`, it breaks.
```scala
package exposure.gui

import scalafx.application.JFXApp

object FirstGui extends JFXApp {
  stage = new JFXApp.PrimaryStage {
    title = "First GUI"
  }
}
```
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at exposure.gui.FirstGui.main(FirstGui.scala)
Caused by: java.lang.NullPointerException
	at scalafx.stage.Stage.title(Stage.scala:115)
	at scalafx.stage.Stage.title_$eq(Stage.scala:118)
	at exposure.gui.FirstGui$$anon$1.<init>(FirstGui.scala:7)
	at exposure.gui.FirstGui$.<init>(FirstGui.scala:8)
	at exposure.gui.FirstGui$.<clinit>(FirstGui.scala:5)
	... 1 more
```

I tried:
```scala
stage.title = ...
```
```scala
stage = new JFXApp.PrimaryStage { title = ... }
```
```scala
// Running on a different main method
FirstGui.stage.title = ""
```
None of these seemed to work. Any advice?

**Comment by jpsacha** [comment]
The issue is with `DelayInit`. While it compiles in dotty, it no longer works as before. Current `JFXApp` does not work in Scala 3. There are a couple of options to deal with that. The most direct one is to use the "standard" JavaFX approach, you can see thet in https://github.com/scalafx/scalafx-hello-world on `Scala3` branch. Another one is a simple upgrade of `JFXApp` where you construct your primary stage in a special function (that you overwrite). I have a working implementation of, I may push an example of that later today. May help in getting examples to work, for now. Third is to use a macro that rewrite `JFXApp` code, on the fly, so it looks similar to current usage (an idea, I do not have it implemented). There may be also some better ways to do this that I did not think about. `JFXApp` is the biggest change moving to Scala 3 that I see short term. Here is an opportunity to make it better.

**Comment by jpsacha** [comment]
@Kalin-Rudnicki there is a crude fix that could be used to port `JFXApp` to Scala 3, demo of usage is here
https://github.com/scalafx/scalafx/blob/77213257c9a4b670c29efb439b71f48c7c75700b/scalafx-demos/src/main/scala/scalafx/JavaFXAnimation.scala

Basically you will need to move code from `JFXApp` constructor to `JFXApp3` method `start`. 

This `JFXApp`:
```scala
object SimpleScalaFXApp extends JFXApp {
  stage = new PrimaryStage {
    title = "Simple ScalaFX App"
    scene = new Scene {
      root = new StackPane {
        padding = Insets(20)
        content = new Rectangle {
          width = 200
          height = 200
          fill = Color.DeepSkyBlue
        }
      }
    }
  }
}
```

can be rewritten using `JFXApp3`:
```scala
object SimpleScalaFXApp extends JFXApp3 {
  override def start() : Unit = {
    stage = new PrimaryStage {
      title = "Simple ScalaFX App"
      scene = new Scene {
        root = new StackPane {
          padding = Insets(20)
          content = new Rectangle {
            width = 200
            height = 200
            fill = Color.DeepSkyBlue
          }
        }
      }
    }
  }
}
```
This requires typing extra `override def start() : Unit = {` but should work till better solution is proposed.

**Comment by OOPMan** [comment]
So besides the `start` trick, nothing else is required to use ScalaFX with Scala 3?

**Comment by jpsacha** [comment]
ScalaFX, build for 2.13, can be used from Scala 3 code.

You can add dependency in SBT using 
```
libraryDependencies ++= "org.scalafx" % "scalafx_2.13" % "15.0.1-R21"
```
or 
```
libraryDependencies ++= ("org.scalafx" %% "scalafx" % "15.0.1-R21").withDottyCompat(scalaVersion.value)
```

There is an example of relatively complex application, [ScalaFX Ensemble](https://github.com/scalafx/scalafx-ensemble), that can be compiled with ether 
 Scala 2.13 or Scala 3.0.0.M1, see branch `Scala_3` (https://github.com/scalafx/scalafx-ensemble/tree/Scala_3).

**Comment by jpsacha** [comment]
I also updated  https://github.com/scalafx/scalafx-hello-world on `Scala3` branch to use `JFXApp3`. Branch `Scala3` compiles for both Scala 3 and Scala 2.13.4

**Comment by OOPMan** [comment]
Thanks!

**Comment by jpsacha** [comment]
Scala 3 support is now merged into the master branch https://github.com/scalafx/scalafx/commit/46ac27955b6731254908020a4157c963e7f7b884
