### ISSUE TITLE
Add type annotations for all public members

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#324]
Many member type annotations for public methods and constants are missing. Those annotations should provide intended explicit conversions from JavaFX types to ScalaFX types. 

Lack of the annotations lead to unintuitive use of ScalaFX API.

**Comment by rom1dep** [comment]
Could also improve build times, I imagine,
did you do that using https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html ?

**Comment by jpsacha** [comment]
@rom1dep As test, I did initial piece by hand with help of IntelliJ inspections. Manually ensuring that types are ScalaFX wherever possible and code style is maintained (like adding prefixes to JavaFX types). Sometimes imports for a specific implicit conversion also needs to be added.

I could imagine that this could be fully automated. 

I did not try [ExplicitResultTypes](https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html). It looks that it will frequently default to JavaFX types. We would need a custom rule. Any ideas how such a rule may be created?

**Comment by rom1dep** [comment]
TBH, I didn't go this far,
while reading about this scalafix rule I found-out that it's not compatible with 2.13, so I ran it from sbt with 2.12 (what gives: https://github.com/rom1dep/scalafx/commits/typeannot , some adjustments indeed required), to then compile it against 2.13.1 and it mostly worked.

(And now I'm noticing that building against 2.13.2 brings a boatload of typing errors, but that doesn't seem related to these changes).

**Comment by jpsacha** [comment]
Looks like most of missing annotations were fixed by recent commits. [ExplicitResultTypes](https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html)  does not detect any no more places where corrections should be made.
