### ISSUE TITLE
TreeTableColumn.cellValueFactory documentation comments

### ISSUE THREAD

**Issue by oleglukin** [scalafx/scalafx#325]
https://github.com/scalafx/scalafx/blob/514f7ca89c708fe6b1241c79e7c0d5b2fa692038/scalafx/src/main/scala/scalafx/scene/control/TreeTableColumn.scala#L296

As a developer I want to use TreeTableColumn to display certain objects.
I tried to follow documentation in this comment, however it didn't work.
```
    * An example of how to set a cell value factory is:
    * {{{
    *   // p.value returns the TreeItem[Person] instance for a particular TreeTableView row,
    *   // p.value.value returns the Person instance inside the TreeItem[Person]
    *   cellValueFactory = { p => p.value.value.firstName }
    * }}}
```
Another user had the same issue and posted a question here:
https://stackoverflow.com/questions/58167773/scala-javafx-cannot-resolve-overloaded-method-add-when-trying-to-add-tree-t
Documentation is a bit difficult to find. I posted a solution [there](https://stackoverflow.com/a/62246371/13229400).

**Comment by jpsacha** [comment]
Thanks for pointing this out. The documentation is missing one `.value` and the comment is off. It should be:

```scala
  cellValueFactory = { p => p.value.value.value.firstName }
```
It also assumes that `Person` is defined with an `ObservableValue` for `firstName, for instance, something like this:
```scala
  class Person {
    val firstName = StringProperty()
    val lastName  = StringProperty()
  }
```

By the way, the StackOverflow question specifically asks how to do it without ScalaFX, using only JavaFX API. That code is actually correct I do not see compilation error mentioned in that question - I do not see anything that needs to be fixed there.

Here is a complete ScalaFX version of the example from http://tutorials.jenkov.com/javafx/treetableview.html:
```scala
import scalafx.application.JFXApp
import scalafx.application.JFXApp.PrimaryStage
import scalafx.beans.property.StringProperty
import scalafx.scene.Scene
import scalafx.scene.control.{TreeItem, TreeTableColumn, TreeTableView}

object TreeTableViewDemo extends JFXApp {

  class Car(brandName: String, modelName: String) {
    val brand = StringProperty(brandName)
    val model = StringProperty(modelName)
  }

  val brandColumn = new TreeTableColumn[Car, String]("Brand") {
    cellValueFactory = p => p.value.value.value.brand
  }

  val modelColumn = new TreeTableColumn[Car, String]("Model") {
    cellValueFactory = p => p.value.value.value.model
  }

  val mercedes = new TreeItem(new Car("Mercedes", "...")) {
    children = Seq(
      new TreeItem(new Car("Mercedes", "SL500")),
      new TreeItem(new Car("Mercedes", "SL500 AMG")),
      new TreeItem(new Car("Mercedes", "CLA 200"))
    )
  }

  val audi = new TreeItem(new Car("Audi", "...")) {
    children = Seq(
      new TreeItem(new Car("Audi", "A1")),
      new TreeItem(new Car("Audi", "A5")),
      new TreeItem(new Car("Audi", "A7"))
    )
  }

  stage = new PrimaryStage {
    title = "TreeTableView CellFactory Demo"
    scene = new Scene {
      root = new TreeTableView[Car] {
        columns ++= Seq(brandColumn, modelColumn)
        root = new TreeItem(new Car("Cars", "...")) {
          children = Seq(audi, mercedes)
        }
      }
    }
  }
}
```

**Comment by oleglukin** [comment]
Thanks @jpsacha 
I was looking for ScalaFX TreeTableView tutorial like this.
