### ISSUE TITLE
Can not access getStyleableNode in javafx.scene.control.TableColumn

### ISSUE THREAD

**Issue by DavidGoodenough** [scalafx/scalafx#329]
According to kleopatra on StackOverflow, the correct way to get the TableColumnHeader (from which table columns can be resized as of JavaFX-14) is to use the column.getStyleableNode method.

Although I using javafx jars 14.0.1 (and this method should have been in many versions before this) the compiler complains that column.getStyleableNode is not part of javafx.scene.control.TableColumn.  getStyleableParent is there, but not getStyleableNode.

I tried removing scalafx.Includes._ to see if that was confusing it, but no luck

I am get the column from a map of the TableView columns, and what I get is the javafx version not a scalafx version.

I have checked the jar file and getStyleableNode is definitely a method defined on TableColumn.

I notice that the scalafx version does provide access to getStyleableParent, but not getStyleableNode.

In the definition of javafx.css.Styleable (which is where TableColumn gets this method), the method is defined as default, but the TableColumn version overrides that with a concrete version that does get the TableColumnHeader.

Any idea why this might be failing?

**Comment by DavidGoodenough** [comment]
Found it, access to this requires that you use java-11 to run Eclipse or sbt as otherwise they can not read parts of the JavaFX JAR files (they are built to 55 not 53).

**Comment by jpsacha** [comment]
Glad that you you were able to figure out the cause.

By the way, I added `styleableNode` method `Styleable` for more Scala-like access.
