### ISSUE TITLE
CheckBoxTreeTableCell.forTreeTableColumn and CheckBoxTableCell.forTableColumn differ 

### ISSUE THREAD

**Issue by DavidGoodenough** [scalafx/scalafx#335]
These two static methods should be about the same (baring the ..TreeTable.. / ..Table.. difference), but they are different.

The TableColumn version seems to work, the TreeTableColumn version seems not to work, giving:-

type mismatch;
 found   : javafx.util.Callback[javafx.scene.control.TreeTableColumn[R,Boolean],javafx.scene.control.TreeTableCell[R,Boolean]]
 required: scalafx.scene.control.TreeTableColumn[R,Boolean] => scalafx.scene.control.TreeTableCell[R,Boolean]

**Comment by jpsacha** [comment]
The ScalaFX code builds and test fine, I do not see that error there. I assume that you are getting the error in your code. Can you provide an example to reproduce the error?

**Comment by DavidGoodenough** [comment]
In the CheckBoxTableCellDemo.scala file there is the following:-
`
          new TableColumn[Item, java.lang.Boolean] {
            text = "Selected"
            // We need to explicitly cast `_.value.selected` to modify boolean type parameters.
            // `scala.Boolean` type is different from `java.lang.Boolean`, but eventually represented the same way
            // by the compiler.
            cellValueFactory = _.value.selected.asInstanceOf[ObservableValue[java.lang.Boolean, java.lang.Boolean]]
            cellFactory = CheckBoxTableCell.forTableColumn(this)
            editable = true
            prefWidth = 180
          }
`
If you change this to TreeTableColumn and CheckBoxTreeTable.forTreeTableColumn you will get the type mismatch I mentioned above.

**Comment by jpsacha** [comment]
Correct implementation of `CheckBoxTreeTableCell.forTreeTableColumn` and added example of use: `CheckBoxTreeTableCellDemo`. In Scala 2.12 and 2.11 the example requires some explicit conversions (`.delegate` calls), so it is added in a 2.12- source tree, rather than complicating Scala 2.13 example.
