### ISSUE TITLE
Mill setup described in ReadMe needs to be corrected

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#343]
Looks that Mill setup described in ReadMe:
```scala
object yourProject extends ScalaModule {

  // Determine OS version of JavaFX binaries
  lazy val osName = System.getProperty("os.name") match {
    case n if n.startsWith("Linux")   => "linux"
    case n if n.startsWith("Mac")     => "mac"
    case n if n.startsWith("Windows") => "win"
    case _                            => throw new Exception("Unknown platform!")
  }

  // Add dependency on JavaFX libraries, OS dependent
  val javaFXModules = List("base", "controls", "fxml", "graphics", "media", "swing", "web")
    .map(m => ivy"org.openjfx:javafx-$m:15.0.1;classifier=$osName")

  def ivyDeps = {
    Agg(
      ivy"org.scalafx::scalafx:15.0.1-R21"
    ) ++ javaFXModules
  }
}
```

Only works with Mill prior to 0.5.3, see discussion here https://users.scala-lang.org/t/javafx-dependency-in-sbt-and-mill/7361 and here https://github.com/com-lihaoyi/mill/issues/767. Suggested solution is: 
```scala
def unmanagedClasspath = T{
    import coursier._, parse.DependencyParser
    val fxMod = Dependency(Module(org"org.openjfx", ModuleName("javafx-controls")), "15.0.1")
    val files = Fetch().addDependencies(fxMod).run()
    val pathRefs = files.map(f => PathRef(os.Path(f)))
    Agg(pathRefs : _*)
  }

def forkArgs = Seq(
   "--module-path", sys.env("JAVAFX_HOME") + ":" +
     "/Users/ajr/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-controls/15.0.1",

    "--add-modules", "javafx.controls"
  )
```
Needs to be verified with ScalaFX. Need somebody with Mill expertise to look into this

**Comment by rom1dep** [comment]
I use a forked mill 0.9.6 with this PR merged: https://github.com/com-lihaoyi/mill/pull/775 so to have coursier determine the classifier (rather than having to pass it through osName like in the first example/sbt), hoping it'll be back to be the default one day :)

None of the dance around javafx-controls resolution/modules passing has ever been required in my case, so I suspect this isn't a typical case. I'll try to have a closer look at that soon©

**Comment by rom1dep** [comment]
@jpsacha I created this repo to demo a working mill config: https://github.com/rom1dep/scalafx-millproject/

It will require https://github.com/com-lihaoyi/mill/pull/775 to be merged and released, though. Thanks @lefou :)

**Comment by jpsacha** [comment]
@rom1dep Thanks for the sample project. Could you add there a README explaining that it requires com-lihaoyi/mill#775?

**Comment by rom1dep** [comment]
Hi @jpsacha , I mentioned this point in the build file of the demo project: https://github.com/rom1dep/scalafx-millproject/blob/master/build.sc#L7

I was thinking of leaving it as such for the moment, waiting for a mill release embedding the change to be cut, and then come-up with a PR with more certain instructions if that sounds ok to you.

**Comment by jpsacha** [comment]
Sounds good to me
