### ISSUE TITLE
Update to Scala 3

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#349]

**Comment by jpsacha** [comment]
https://github.com/scalafx/scalafx/commit/56530db7ad4e861a45e1ec940d326cd4ac9958e5

**Comment by rom1dep** [comment]
Was a non-RC version subsequently published to maven?

Here the latest points to RC3: https://repo1.maven.org/maven2/org/scalafx/

**Comment by jotomo** [comment]
@rom1dep https://repo1.maven.org/maven2/org/scalafx/scalafx_3/
The way I understood it, all Scala 3.x versions will be compatible, so after `scala_3.0.0-RC3` comes plain `scala_3` :-)

**Comment by jpsacha** [comment]
This issue just marks SBT change. The binaries for Scala 3 are actually
published earlier today. Takes a couple hours before they show up on maven
repo. They are there now.

**Comment by rom1dep** [comment]
Seeing it now, thanks and sorry for the noise!

**Comment by jpsacha** [comment]
FYI: release 16.0.0-R23 for Scala 3 has a problem, dependency on Scala 2.13 reflect library (#355). I will be releasing new version, 16.0.0-R24, soon that corrects that issue. That issue was already in 16.0.0-R22 for Scala 3.0.0-RC3, but I just noticed it.
