### ISSUE TITLE
Update scaladoc demos to use JFXApp3

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#352]
See for instance here: https://oss.sonatype.org/service/local/repositories/releases/archive/org/scalafx/scalafx_2.13/16.0.0-R23/scalafx_2.13-16.0.0-R23-javadoc.jar/!/index.html

**Comment by rom1dep** [comment]
```
➤ rg JFXApp -g "*.scala" scalafx-demos -c | wc -l
99
➤ rg JFXApp -g "*.scala" scalafx -c | wc -l     
22
```
I wonder how hard it is to write a source transformer from scalameta, seems justified in this case :)

**Comment by jpsacha** [comment]
Automatically transforming the code would be quite helpful. Would you be able to look into this?

**Comment by rom1dep** [comment]
I have no experience with that, but it sounds fun enough (based on the examples on https://scalameta.org/docs/trees/guide.html#transform-trees )

Would those two rules be relevant/enough, in your opinion:

- imports
  - transform `scalafx.application.JFXApp` into `scalafx.application.JFXApp3`
  - transform `scalafx.application.JFXApp.PrimaryStage` into `scalafx.application.JFXApp3.PrimaryStage`
- "main" object
  - transform `object XYZ extends JFXApp` into `object XYZ extends JFXApp3`
  - create new method `start()` for `object XYZ`: `override def start(): Unit`
  - move all members of `object XYZ` into `start()`

**Comment by jpsacha** [comment]
Those rule should work in most cases. There my be some corner cases that use declarations like `private val`, like in demo `scalafx.controls.PaginationSample`,  but those could be fixed by removing `private` by hand.

**Comment by rom1dep** [comment]
so, I finally wrote a scalafix rule here: https://github.com/rom1dep/scalafx_scalafix_jfxapp3
and pushed the result there: https://github.com/scalafx/scalafx/pull/356

As it happens, scalafix doesn't make it practical to conserve formatting when implementing a rewrite rule, so I ran `scalafmt` before and after the rewrite, which makes this PR a bikeshed of its own (I tried to adapt `.scalafmt.conf` to minimize the diff, though).

The effect of the rewrite itself lies in this commit: https://github.com/scalafx/scalafx/pull/356/commits/73f94c616ae7c800162ce1f6a260fa23ce60c063 (before is just preparing the project and running scalafmt)

After the rewrite, some fine-tuning was needed for demos to compile: https://github.com/scalafx/scalafx/pull/356/commits/68d1c999060a1bd9b1bb84d71e9512e19030131a (probably not everything is legit, the style of some demos was "not great" and I didn't want to spend too much time rewriting a lot of it)

I haven't tested most demos yet, that will be a task for another day

For the curious, the scalafix rewrite rule can be run by:
- cloning https://github.com/rom1dep/scalafx_scalafix_jfxapp3 at the root of the scalafx repo
- running `scalafix --rules=file:scalafix/rules/src/main/scala/fix/JFXApp3Migration.scala` in sbt with the patched build.sbt of the PR

**Comment by jpsacha** [comment]
@rom1dep Looks that we need a more consistent way of formatting the code. I will open issue for that and start with setup that you had in PR #356

**Comment by jpsacha** [comment]
I think all uses of JFXApp in ScalaFX project are now converted to JFXApp3
