### ISSUE TITLE
Cannot set app icon

### ISSUE THREAD

**Issue by unikub0** [scalafx/scalafx#358]
I try to set up icon for my app project, but this was happen

> Exception in Application start method
> Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.lang.NullPointerException: Input stream must not be null
> 	at javafx.scene.image.Image.validateInputStream(Image.java:1135)
> 	at javafx.scene.image.Image.<init>(Image.java:702)
> 	at scalafx.scene.image.Image.<init>(Image.scala:47)
> 	at id.unikub.platShot.SimpleScalaFXApp$$anon$3.<init>(Main.scala:26)
> 	at id.unikub.platShot.SimpleScalaFXApp$$anon$1.<init>(Main.scala:30)
> 	at id.unikub.platShot.SimpleScalaFXApp$.start(Main.scala:31)
> 	at scalafx.application.JFXApp3.main$$anonfun$1(JFXApp3.scala:287)
> 	at scalafx.application.JFXApp3.init$$anonfun$1(JFXApp3.scala:302)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
> 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
> 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
> 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
> 	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
> 	at scalafx.application.JFXApp3.init(JFXApp3.scala:302)
> 	at scalafx.application.JFXApp3.init$(JFXApp3.scala:237)
> 	at id.unikub.platShot.SimpleScalaFXApp$.init(Main.scala:16)
> 	at scalafx.application.AppHelper3.start(AppHelper3.scala:33)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
> 	... 1 more

and here the code
```scala
package id.unikub.platShot

import scalafx.application.JFXApp3
import scalafx.scene.Scene
import scalafx.geometry.Insets
import scalafx.scene.shape.Rectangle
import scalafx.scene.paint.Color
import scalafx.stage.Screen
import scalafx.scene.control.Button
import scalafx.scene.Group
import scalafx.scene.layout.BorderPane
import scalafx.scene.layout.HBox
import scalafx.scene.layout.VBox
import scalafx.geometry.Pos
import scalafx.scene.image.Image
object SimpleScalaFXApp extends JFXApp3:
  override def start() : Unit =
    val playBtn = Button("Play")
    val optBtn = Button("Options")
    val quitButton = Button("Quit")
    val mainMenu = VBox(playBtn, optBtn, quitButton)
    mainMenu.alignment = Pos.CenterRight
    stage = new JFXApp3.PrimaryStage{
      scene = new Scene{
        title = "plat-Shot"
        icons += (Image(this.getClass.getResourceAsStream("/icon/plat-Shot logo.png")))
        root = new BorderPane{
          center = mainMenu
        }
      }
    }
```
i place the file at src/main/resource/icon
can someone help me?

**Comment by rom1dep** [comment]
does it work with prefixing `resource` to the path? Ideally start with a path not containing whitespace.

**Comment by unikub0** [comment]
> In my code I use the equivalent of `icons += new Image("icon/plat-Shot logo.png")`. So just the relative file path below the resources folder. HTH.
Oh i got it. I renamed the folder with "resources" and its working. Thanks
