### ISSUE TITLE
There are places in code where `Some(x)` is used incorrectly to create values, instead of `Option(x)`

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#359]
For instance in `Dialog`:

```scala
  def showAndWait[F](j2s: F = (x: R) => x)(implicit convert: DConvert[R, F]): Option[convert.S] = {
    val v = delegate.showAndWait()
    if (v.isPresent) Some(convert(v.get, j2s)) else None
  }
```

In IntelliJ those places can be located using "Some to Option" inspection

**Comment by Facsimiler** [comment]
@jpsacha That example looks like a valid use of `Some`. Why is that wrong? Is it a false positive in _IntelliJ_? Just curious...

**Comment by jpsacha** [comment]
Maybe not a best example, but in general one can get burned assuming that argument to `Some` is not `null`, and it is not always easy to find out where problem is coming from. I just recently got into problem when working with result returned by `Dialog`. At the end the issue was not in `Dialog`, but that way some across some of the uses of `Some`. In my experience, one should use `Some` in pattern matching, but create instances using `Option`, it will check for `null` .
