### ISSUE TITLE
HelloStageDemo crash

### ISSUE THREAD

**Issue by roncoleman125** [scalafx/scalafx#361]
I followed your instructions using sbt and while everything compiled successfully, the HelloStageDemo crashed as follows for my mac M1:
Sep 10, 2021 9:29:17 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5af02540'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError:
...
Did I missing something?

**Comment by jpsacha** [comment]
I do not have M1 to verify how it works there.
The warning:
```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5af02540'
```
is from JavaFX, due to SBT and Java module system. It is only a warning should not have impact.

Error:
```
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError:
```
indicates some installation issue with JavaFX, maybe wrong version of JavaFX is installed or some pieces missing.

**Comment by jpsacha** [comment]
@somatoko do you have
```sbt
fork := true
```
in your `build.sbt`? It will do `run` in a separate JVM, loading new JavaFX libraries each time
