### ISSUE TITLE
Support for JavaFX 17 

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#362]
Main roadblock is bug in SBT https://github.com/sbt/sbt/issues/6564 that incorrectly resolved JavaFX platform dependent JARs

**Comment by rom1dep** [comment]
Can confirm I can compile scalafx with Java 17 against JavaFX 17 with this patch: https://github.com/coursier/coursier/pull/2176

Also, the usual "naive API check" doesn't bring up too much novelty this time:
```
 rg "@since 17" -c ./modules/javafx.* -g '!*module-info.java'
./modules/javafx.graphics/src/main/java/javafx/scene/SpotLight.java:1
./modules/javafx.graphics/src/main/java/javafx/css/Stylesheet.java:1
./modules/javafx.graphics/src/main/java/javafx/application/Platform.java:1
./modules/javafx.graphics/src/main/java/javafx/print/JobSettings.java:1
./modules/javafx.controls/src/main/java/javafx/scene/control/TreeTableCell.java:3
./modules/javafx.controls/src/main/java/javafx/scene/control/SkinBase.java:4
```

**Comment by jpsacha** [comment]
@rom1dep did you rebuild SBT too to use that coursier?

**Comment by rom1dep** [comment]
No, I don't know SBT enough to adventure in it.
I built coursier's master branch and published it locally, then built a local mill version that depends on it, and finally compiled scalafx using mill with `mill-release scalafx[3.0.2].compile` and this mill build file: https://github.com/rom1dep/scalafx/blob/mill/build.sc

**Comment by s-bernard** [comment]
To use javafx 17 directly, you can use mill and set a `resolutionCustomizer` to:
```
  def resolutionCustomizer =
    T.task {
      Some((r: coursier.core.Resolution) =>
        r.withOsInfo(
          coursier.core.Activation.Os.fromProperties(sys.props.toMap),
        ).withExtraProperties(Seq(("javafx.monocle", "false")))
      )
    }
```
