### ISSUE TITLE
NPE in TableColumn.cellValueFactory_=

### ISSUE THREAD

**Issue by s-bernard** [scalafx/scalafx#371]
In:
https://github.com/scalafx/scalafx/blob/e9cb926d0ab4e26f1d0970f0d33ee4f11f005a1b/scalafx/src/main/scala/scalafx/scene/control/TableColumn.scala#L320
if `f(v)` return null, we get a NPE. However, it is a totally acceptable value for javafx to return `null` here.

Suggested fix, replace line 320 by `Option(f(v)).map(_.delegate).getOrElse(null)`.

Maybe a future solution would be to change `f` to be `f: TableColumn.CellDataFeatures[S, T] => Option[ObservableValue[T, T]]` to limit the number of Option wrapping as discussed in #370.

**Comment by jpsacha** [comment]
@s-bernard  can you create a PR with the suggested fix? 
`Option(f(v)).map(_.delegate).getOrElse(null)`

Looks that this needs to be done for `TableColumn` and `TreeTableColumn`

Let's keep the signature for `f` as it is for now

**Comment by s-bernard** [comment]
Yes, OK
