### ISSUE TITLE
Installing Tooltips for a Node that is not a member of control

### ISSUE THREAD

**Issue by Hungreeee** [scalafx/scalafx#378]
Hi, I was trying to install Tooltips for a Node that is a part of my Pie Chart using ScalaFX (def setTooltip not available). However, I found out that this implementation is deprecated. I searched the Internet up and down but had no luck. How is this implemented? I really think you should allow setTooltip for all Nodes other than just the member of control. 
![image](https://user-images.githubusercontent.com/46376260/159570914-bc3cc448-b53e-4b2c-a4b0-df1b72f0d0b0.png)

**Comment by jpsacha** [comment]
Please check the updated version of the [example](https://github.com/scalafx/scalafx/issues/210#issuecomment-1075779207) in issue #210. 

There is a "glitch" in current API when you use mixed types (one ScalaFX one JavaFX) in call to `Tooltip.install` - you could get compilation error `ambiguous reference to overloaded definition`.

A workaround is to make both arguments of `Tooltip.install` have ScalaFX types, for instance, to replace line
```scala
val sliceNode = d.getNode
```
with 
```scala
import scalafx.scene.Node
...
val sliceNode : Node = d.getNode
```
or 
```scala
import scalafx.scene.Node
...
val sliceNode : Node = d.node()
```
This way `sliceNode` and `tt` are both ScalaFX types

The fix to API is possible but not trivial (#377). The workaround above should work for now.

**Comment by Hungreeee** [comment]
![image](https://user-images.githubusercontent.com/46376260/160253842-4da4c947-b70a-463c-ba0e-ccf99c2aeb59.png)
This expression is not valid as the d.getNode is a JavaFX Node.

**Comment by jpsacha** [comment]
Please make sure that you include ScalaFX implicit conversions in you code:
```scala
import scalafx.Includes._
```

**Comment by Hungreeee** [comment]
It works perfectly! Thank you so much!
