### ISSUE TITLE
How to switch between multiple scenes?

### ISSUE THREAD

**Issue by mattseburn** [scalafx/scalafx#387]
I'm relatively new to scalafx (and javafx), so maybe I'm missing something obvious.  But I can't seem to see how to make this work.

I'm creating a simple game that consists of multiple "screens" (currently modeled via `Scene`), such as a loading screen and the main game screen.  I want to be able to treat these as self contained units, so I can just "activate" one or the other as a whole.

I want to be able to use this pattern for managing them:
```
new Rectangle {
  fill <== when (hover) choose Green otherwise Red
}
```

but the `<==` operator doesn't seem to be available for the `scene` property on `PrimaryStage`.  Here is a code snippet:
```
object Platformer extends JFXApp3 {
  override def start(): Unit = {
    stage = new PrimaryStage {
      title.value = "Hello stage"
      width = 600
      height = 500

      // cannot resolve symbol <==
      scene <== when(GameState.currentScene === "loading") choose LoadingScene() otherwise GameScene()
    }
  }
}
```

`GameState.currentScene` is a string property declared as follows:
```
object GameState {
  val currentScene: StringProperty = new StringProperty("loading")
}
```

`LoadingScene` and `GameScene` both return instances of `Scene`.

According to what I'm seeing online, javafx at least supports changing between multiple scenes in the primary stage.  What am I doing wrong?  Is there a better way to do what I'm trying to do?

Thanks!

**Comment by jpsacha** [comment]
The `scene` property of a Stage is read-only property. You can not use '<==' to bind to it/change its values. You need to use setter. Something like this may work:
```scala
      (GameState.currentScene).onChange{ (_,_,newValue) =>
        if(newValue == "loading") 
          scene = LoadingScene()
        else 
          scene = GameScene()
      }
```

**Comment by mattseburn** [comment]
That worked perfectly, thank you!
