### ISSUE TITLE
[JavaFX 21] `GridPane` has a new constructor: `GridPane(double hgap, double vgap)`

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#399]
https://openjfx.io/highlights/21/

**Comment by objektwerks** [comment]
Can you give us an idea of what it will **_take_** to:

1. make ScalaFx compatible with JDK 21 JavaFx; and
2. deliver a ScalaFx 21

I currently use ScalaFx with JDK 21. Thanks!

**Comment by jpsacha** [comment]
The are few places in JavaFX 21 API that changes compared to JavaFX 20. If you do not use specific API you may be able to run ScalaFX 20 with JavaFX 21. To provide better compatibility some things needs to be added or changed in ScalaFX. This one, the new constructor for GridPane is one of the smaller changes. More info about changes in JavaFX 21 API can be found here:  https://openjfx.io/highlights/21/

The ScalaFX unit test can detect more problematic changes. Those were my primary interest, see details in the milestone [21.0.0-R32](https://github.com/scalafx/scalafx/milestone/33).

**Comment by objektwerks** [comment]
Excellent! Thanks so much for your update and hard work! Cheers!
