### ISSUE TITLE
Creating scala project via SBT

### ISSUE THREAD

**Issue by StanCDev** [scalafx/scalafx#402]
When creating a new sbt project with the `sbt new scalafx/scalafx.g8` command I get the following error/warning messages.

 `
[info] running (fork) my.scalafx.ScalaFXHelloWorld
`
`
[error] Dec 27, 2023 10:18:33 AM com.sun.javafx.application.PlatformImpl startup
`
`
[error] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4b0a425f'
`
`
[error] Dec 27, 2023 10:18:38 AM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
`
`
[error] WARNING: Timeout while waiting for app reactivation
`

The sequence of commands I ran are:
`sbt new scalafx/scalafx.g8` 
`sbt` 
`run` 

Also, the first time I click on the ScalaFx window there seems to be this bug where it flickers once.
A part from that other bug, the ScalaFx window seems to be working well despite these messages. 
If this is of any use this has been run on MacOS

Are the warning supposed to be there? Is there a way to fix this?

**Comment by jpsacha** [comment]
The warning is the SBT issue, the way it loads Java modules.

On recent versions there is an issue with JavaFX 21. It is fixed with JavaFX 21.0.1. ScalaFX 21.0.0-R32 is adding JavaFX 21 by default, it can be overwritten I will add additional info later.

**Comment by jpsacha** [comment]
Here is an example how to explicitly set dependency on a specific version of JavaFX. In the `build.sbt` add this line
```sbt
libraryDependencies ++= Seq("base", "controls", "fxml", "graphics", "media", "swing", "web")
                         .map(m => "org.openjfx" % s"javafx-$m" % "21.0.1")
```
It will setJavaFX version to 21.0.1, that dies not flicker (and starts faster on recent macOS)

**Comment by jpsacha** [comment]
Also, if running application from within SBT you get a runtime warning:
```
   [error] ... com.sun.javafx.application.PlatformImpl startup
   [error] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module ...'
```
You can suppress the warning by adding the following to  SBT's project configuration:
```scala
Compile / run / javaOptions ++= Seq(
  "--module-path", (Compile / dependencyClasspath).value
                                                  .files
                                                  .filter(_.name.toLowerCase.contains("javafx"))
                                                  .mkString(java.io.File.pathSeparator),
  "--add-modules", "javafx.graphics",
  "--enable-native-access=javafx.graphics"
)
```
