### ISSUE TITLE
Questions about ScalaFX Demos chart

### ISSUE THREAD

**Issue by l7u7ch** [scalafx/scalafx#403]
I have a question about ScalaFX Demos charts.

https://github.com/scalafx/scalafx/tree/master/scalafx-demos/src/main/scala/scalafx/scene/chart

Do you need the following code?

`import scalafx.scene.chart._`

**Comment by objektwerks** [comment]
Yes, you will need that import to work with ScalaFx charts. Here are some more examples as to why:

[PoolBalance Charts](https://github.com/objektwerks/pool.balance/tree/main/client/src/main/scala/pool/chart)

You might prefer using detailed imports, like this: ```import scalafx.scene.chart.{LineChart, XYChart}```

**Comment by l7u7ch** [comment]
Thank you, @objektwerks 

I hope this is fixed.
